# Example configuration for LijnDing pipelines.
# This file is used by the `07_configuration.py` example.

processing:
  greeting: "Hello from config"
  punctuation: "!!!"

# This value is not used in the example, but shows that you can have
# other configuration sections.
app_settings:
  log_level: "INFO"
  retries: 3
